import { ReactElement } from 'react'
import Head from 'next/head'
import Container from '@/components/Container'
import HeaderNav from '@/components/HeaderNav'
import Footer from '@/components/Footer'
import { GetStaticPropsContext } from 'next'
import { useTranslations } from 'next-intl'
import Image from 'next/image'

export default function Home() {
  const t = useTranslations("DocTitle")

  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image
          src="https://images.pexels.com/photos/1576667/pexels-photo-1576667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          alt="Main Cover Image"
          width={1260}
          height={500}
          quality={100}
          className="object-cover sm:w-screen h-[92.5vh]"
        />
        {/* <img src="https://images.pexels.com/photos/1576667/pexels-photo-1576667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          alt="Main Cover Image"
          className="object-cover sm:w-screen h-[92.5vh]"
          loading='eager'
        /> */}
      </div>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Container>
      <HeaderNav/>
      {page}
      <Footer/>
    </Container>
  )
}

export async function getStaticProps(context: GetStaticPropsContext) {  
  return {
    props: {
      messages: (await import(`../messages/${context.locale}.json`)).default
    }
  }
}
